Yokohama-Miyazawa/Ripple

View/Users/admin_edit.ctp
=> Course fix/1

View/Users/admin_edit.ctp
=> ユーザ編集からコース設定機能を削除．

Controller/RecentstatesController.php, Model/Soap.php, Model/User.php, View/RecentStates/admin_group_view.ctp
=> 近況状況を見られない不具合を修正．

Controller/RecentstatesController.php, Model/User.php, View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp
=> 近況状況に学年表示機能を追加．

Controller/RecentstatesController.php, Controller/SoaprecordsController.php, Model/Soap.php, View/Elements/admin_menu.ctp, View/SoapRecords/admin_index.ctp, webroot/css/admin.css, webroot/css/elements.css
=> SOAP一覧閲覧機能を追加．

View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp, View/SoapRecords/admin_index.ctp, webroot/css/recentstate.css, webroot/css/soapview.css
SOAPに長い文章を入力しても，近況状況およびSOAP一覧での表示が崩れない様に修正．
=> Soap view/5

Controller/RecentstatesController.php, Controller/SoaprecordsController.php, Model/Course.php, View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp, webroot/css/soapview.css
=> 教材進捗表示機能を追加．

Controller/RecentstatesController.php, Controller/SoapsController.php, Model/Record.php, Model/Soap.php, View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp
近況状況にて，SOAP記入時に受講生がどこまで教材を進めたか表示される．
ib_soapsテーブルのcurrent_stateカラムの後ろに，studied_contentカラムが追加された．
=> 近況状況に学習教材表示機能を実装．

Controller/RecordsController.php, Controller/SoaprecordsController.php, Model/Soap.php, View/SoapRecords/admin_index.ctp
=> SOAP一覧画面にCSVダウンロード機能を追加．

View/Elements/admin_menu.ctp, View/RecentStates/admin_group_view.ctp
=> メニューバーと近況状況グループ閲覧を修正．

Controller/SoaprecordsController.php, View/SoapRecords/admin_index.ctp
SOAP記録閲覧画面にて，グループ検索を記入式から選択式に変更．
=> SOAP記録閲覧画面にて，グループ検索を記入式から選択式に変更．

View/Enquete/admin_index.ctp, View/Enquete/records.ctp, View/SoapRecords/admin_index.ctp, webroot/css/admin.css, webroot/css/enquete.css
=> SOAP一覧にソート機能追加．検索一覧のデザイン修正．

Model/Record.php, Model/User.php
UserモデルとRecord, Soap, Enqueteの各モデルとの間の依存関係を設定．
=> UserモデルとRecord, Soap, Enqueteの各モデルとの間の依存関係を設定．

Controller/EnqueteController.php, View/Enquete/index.ctp
=> ユーザIDを変更して，別ユーザとしてアンケート投稿できてしまう不具合を修正．

webroot/css/recentstate.css, webroot/css/soap.css
=> グループ選択ボタンの文字サイズを拡大．

Controller/EnqueteController.php, Model/Enquete.php, View/Enquete/admin_index.ctp
=> アンケートにCSV出力機能を追加．

View/Users/login.ctp
受講者ログインページから，管理者ログインページへのリンクを削除．
=> 受講者ログインページから，管理者ログインページへのリンクを削除．

Controller/RecentstatesController.php, Model/Soap.php, View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp
=> 近況状況ページに記入者の名前を表示．

Controller/EnqueteController.php, Controller/UsersCoursesController.php, View/Enquete/index.ctp
=> アンケート編集機能を追加

Config/database.php, Console/Command/AppShell.php, Console/Command/TokenShell.php, Console/cake, Console/cake.bat, Console/cake.php, Model/Token.php, View/Emails/text/password_recover.ctp
パスワード再設定時のトークンを削除する機能を修正．自動化するにはcrontabを手動設定する必要あり．
=> パスワード再設定時のトークンを削除する機能を修正．自動化するにはcrontabを手動設定する必要あり．

View/Contents/index.ctp
教材は全部表示されるが，前の教材がクリアしないと次の教材をアクセスできないようにした．
=> 教材表示に関する修正

Controller/EnqueteController.php, Model/Enquete.php, View/Enquete/index.ctp
アンケートの必須項目は
　担当講師
　今日のゴール
のみに変更した．
入力した担当講師のグループに，自動的に所属するようになった．
=> アンケートの記入に関する修正

Controller/RecentstatesController.php, Model/User.php, View/Elements/admin_menu.ctp, View/RecentStates/admin_all_view.ctp, View/RecentStates/admin_index.ctp
=> 全受講生の近況状況を一度に見られる機能を追加．

View/Layouts/default.ctp
画面左上部のリンクから管理者ページ<->利用者ページを移動可能化．管理者のみの機能．
=> 画面左上部のリンクから管理者ページ<->利用者ページを移動可能化．

View/Users/admin_login.ctp, View/Users/login.ctp
=> ログイン画面のデザインを変更

View/RecentStates/admin_group_view.ctp, View/Soaps/admin_group_edit.ctp
SOAPのグループ編集および閲覧時に，所属受講生がいない場合はそのことを伝えるメッセージを追加．
=> SOAPのグループ編集および閲覧時に，所属受講生がいない場合はそのことを伝えるメッセージを追加．

Controller/SoapsController.php, View/Soaps/admin_group_edit.ctp, View/Soaps/admin_student_edit.ctp, webroot/css/recentstate.css, webroot/css/soap.css
=> SOAP記入の際に受講生の顔写真を表示．

Controller/UsersController.php, View/Users/email_setting.ctp
メールアドレス設定で，形式に則っていない入力に対して警告を出す．
=> メールアドレス設定で，形式に則っていない入力に対して警告を出す．

Controller/RecentstatesController.php, View/RecentStates/admin_all_view.ctp, View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp, webroot/css/soapview.css
近況状況に受講生番号表示機能を追加．
近況状況をグループまたは全受講生で表示した際の，各受講生間のブロックにボーダー表示を追加．
=> 近況状況に受講生番号表示機能を追加．

Model/Content.php, Model/ContentsQuestion.php, Model/Course.php, Model/User.php
=> 直書きのSQL文を一部削除．

Model/Content.php, Model/Course.php
CourseおよびContentとRecordの間のモデル依存関係を設定．
=> CourseおよびContentとRecordの間のモデル依存関係を設定．

Model/Course.php, Model/Record.php, View/RecentStates/admin_all_view.ctp, View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp
=> Design fix/1

Controller/DatesController.php, Model/Attendance.php
各種管理->授業日->対応する授業日の編集->保存すると，
新規ユーザーに追加されていない出席情報が追加されるようになる．
=> 出席管理機能を一部修正

Controller/AttendancesController.php, Controller/UsersController.php, Model/User.php, View/AdminManages/admin_index.ctp, View/Attendances/admin_index.ctp, View/RecentStates/admin_all_view.ctp, View/RecentStates/admin_find_by_student.ctp, View/Soaps/admin_find_by_student.ctp, View/Users/admin_index.ctp
Reverts Yokohama-Miyazawa/Ripple#151
=> Revert "ユーザ画像の表示を、一部Controllerを介して行うように変更。"

Controller/EnqueteController.php, Controller/RecentstatesController.php, Controller/SoaprecordsController.php, Controller/UsersController.php, Controller/UsersCoursesController.php, Model/Record.php, Model/User.php, View/Enquete/admin_index.ctp, View/RecentStates/admin_student_view.ctp, View/SoapRecords/admin_index.ctp, View/Users/admin_index.ctp
ダッシュボード、アンケート、SOAPの表示に関する軽量化を実施。
=> Heavy sql/2

Controller/EnqueteController.php, Controller/RecentstatesController.php, Controller/SoaprecordsController.php, Controller/UsersController.php, Controller/UsersCoursesController.php, Model/Course.php, Model/Record.php, Model/User.php, View/Enquete/admin_index.ctp, View/RecentStates/admin_all_view.ctp, View/RecentStates/admin_group_view.ctp, View/RecentStates/admin_student_view.ctp, View/SoapRecords/admin_index.ctp, View/Users/admin_index.ctp
=> Heavy sql/3

Config/Schema/app.sql, Controller/EnqueteController.php, Model/Course.php, Model/Group.php, Model/User.php, Model/UsersCourse.php, View/Soaps/admin_group_edit.ctp
関連コミット
https://github.com/Yokohama-Miyazawa/Ripple/commit/392b99ce54d779f95c7290bba382edbf5d1cf8e6 https://github.com/Yokohama-Miyazawa/Ripple/commit/d3d14626c305b8cf2f425217e2eab8cf6e03a60b https://github.com/Yokohama-Miyazawa/Ripple/commit/c7e9445fc1caf09d8fa3b2b1d158e81ad9ef044b
=> Userテーブルにあった、直近の所属グループを記録する `last_group` を削除。

Controller/AttendancesController.php, Controller/ContentsQuestionsController.php, Controller/RecentstatesController.php, Controller/RecordsController.php, Controller/UsersCoursesController.php, Model/Course.php, Model/User.php, Model/UsersCourse.php, View/Attendances/admin_index.ctp, View/Users/admin_edit.ctp, View/UsersCourses/index.ctp
設定はユーザ編集画面から可能。
受講生は受講コースに設定されているコースのみ閲覧可能。
受講生近況画面でも、その受講生が受講しているコースの教材進捗のみ表示される。
=> 受講生毎に受講コースを設定できるように変更。

Controller/SoapsController.php, View/Soaps/admin_group_edit.ctp, View/Soaps/admin_student_edit.ctp, webroot/css/soap.css
SOAP入力画面にて、「今日の授業のゴール」「今日のゴールは達成できたか」、
達成できなかった場合は「今日のゴールを達成できなかった理由」を表示するように修正。
また、SOAP入力画面表示の際にアンケートを取得する条件を「今日だけ」から「最後の授業日から今まで」に修正。
=> SOAP入力画面に表示するアンケート内容を追加

Controller/EnqueteController.php, Controller/SoapsController.php
関連Commit: https://github.com/Yokohama-Miyazawa/Ripple/commit/a0212d88bc163252a7034e5099d21cb79c903556
=> アンケートおよびSOAPで選択したグループがユーザ情報にも反映されるように修正。

Controller/UsersCoursesController.php, Model/Attendance.php, View/UsersCourses/index.ctp, webroot/css/user_course.css
CSSの参考URL: https://web.monogusa-note.com/flexible-tabs-only-css
余計な変更を差し戻して再度プルリクエスト
=> 授業日ログイン時のモーダルウィンドウで欠席連絡できるように修正。 

Controller/SoapsController.php
参考URL
https://book.cakephp.org/2/ja/core-libraries/components/security-component.html
https://junichi11.com/cakephp-2/cakephp2-0-securitycomponentで二重送信防止
=> SOAPの二重投稿を防止。

Controller/EnqueteController.php, View/Enquete/admin_edit.ctp, View/Enquete/admin_index.ctp, View/Enquete/index.ctp, View/Enquete/records.ctp, View/UsersCourses/index.ctp, webroot/css/image-selector.css, webroot/js/image-selector.js
データベースのib_groupsテーブルに、そのグループのリーダー講師を示すカラム`leader_id`を追加する必要あり。
下記ライブラリを使用。
https://mo2nabe.com/demo-image-selector/
https://gist.github.com/motsu0/a208f55d3272d36c8cf390124d330324
=> 受講生側のアンケート入力画面にて、講師選択の際に講師の顔写真を表示。

Controller/SoapsController.php
関連 Pull Request: https://github.com/Yokohama-Miyazawa/Ripple/pull/243
=> SOAPの二重投稿を防止に関する処理を修正。グループでのSOAP投稿ができなくなっていたのを解決。
